### ISSUE TITLE
Add a poll mode to test

### ISSUE THREAD

**Issue by sjagoe** [sjagoe/usagi#40]
This will allow testing an asynchronous update that is caused by a previous test.

**Comment by sjagoe** [comment]
Example test:
```yaml
cases:
  - name: "Test an asynchronous event"
    tests:

      - name: "Delete object"
        url:
          type: template
          template: "/object/path/1"
        parameters:
          method: DELETE
          headers:
            Authorization: "Basic <abc123>"
        assertions:
          - name: status_code
            expected: 204

      - name: "Wait for object deletion to complete"
        url:
          type: template
          template: "/object/path/1"
        poll:  # poll every second up to 5 seconds.
          period: 1
          timeout: 5
        parameters:
          headers:
            Authorization: "Basic <abc123>"
        assertions:
          - name: status_code
            expected: 404
```
